tasker/urls.py
from django.urls import path
from django.conf import settings
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

from .views import nick, board, tasks, handlings, attachments

urlpatterns = [
    path('', TemplateView.as_view(template_name='meta/start.html'), name='start'),
    path('meta/learn-more', TemplateView.as_view(template_name='meta/learn-more.html'), name='learn_more'),
    path('meta/imprint', TemplateView.as_view(template_name='meta/imprint.html'), name='imprint'),

    path('board/<slug:board_slug>/enter_nick', nick.EnterNickView.as_view(), name='enter_nick'),
    path('board/<slug:board_slug>/reset_nick', nick.ResetNickView.as_view(), name='reset_nick'),

    path('create_board/', board.CreateBoardView.as_view(), name='create_board'),

    path('board/<str:board_hash>/admin', board.BoardAdminView.as_view(), name='board_admin'),
    path('board/<str:board_hash>/edit', board.EditBoardView.as_view(), name='edit_board'),
    path('board/<str:board_hash>/delete', board.DeleteBoardView.as_view(), name='delete_board'),
    path('board/<str:board_hash>/create_task', tasks.CreateTaskView.as_view(), name='create_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/quickdone', tasks.QuickDoneTaskView.as_view(), name='quickdone_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/set_lock', tasks.SetLockTaskView.as_view(), name='set_task_lock'),
    path('board/<str:board_hash>/tasks/<int:task_id>/reset', tasks.ResetTaskView.as_view(), name='reset_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/edit', tasks.EditTaskView.as_view(), name='edit_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/delete', tasks.DeleteTaskView.as_view(), name='delete_task'),

    path('board/<slug:board_slug>', board.BoardView.as_view(), name='show_board'),
    path('board/<slug:board_slug>/monitor', board.BoardMonitorView.as_view(), name='board_monitor'),
    path('board/<slug:board_slug>/summary', board.BoardSummaryView.as_view(), name='board_summary'),
    path('board/<slug:board_slug>/tasks', tasks.TaskListView.as_view(), name='list_tasks'),
    path('board/<slug:board_slug>/request_link', board.BoardSendAdminLinkView.as_view(), name='request_board_link'),

    path('board/<slug:board_slug>/task/<int:task_id>', tasks.TaskView.as_view(), name='show_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/start', handlings.StartTaskView.as_view(), name='create_handling'),
    path('board/<slug:board_slug>/task/<int:task_id>/comment', handlings.CommentTaskView.as_view(), name='comment_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/abort', handlings.AbortTaskView.as_view(), name='abort_handling'),
    path('board/<slug:board_slug>/task/<int:task_id>/complete', handlings.CompleteTaskView.as_view(), name='complete_handling'),
    path('board/<slug:board_slug>/task/<int:task_id>/lock', tasks.LockTaskView.as_view(), name='lock_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/unlock', tasks.UnlockTaskView.as_view(), name='unlock_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/attachment/<int:attachment_id>/preview', attachments.PreviewView.as_view(), name='preview_attachment'),
    path('board/<slug:board_slug>/task/<int:task_id>/attachment/<int:attachment_id>/fetch', attachments.FetchView.as_view(), name='fetch_attachment'),

    path('sw.js', TemplateView.as_view(template_name='tasker/sw.js', content_type='text/javascript'), name='jssw'),
    path('app.js', TemplateView.as_view(template_name='tasker/app.js', content_type='text/javascript', extra_context={'push_pubkey': settings.WEB_PUSH_KEYS[0]}), name='jsapp'),
    path('register_webpush', nick.StoreWebPushView.as_view(), name='webpush_register'),
    # TODO add caching
    path('jsi18n.js', JavaScriptCatalog.as_view(), name='jsi18n'),
]

troodle/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404

from tasker.views.start import error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasker.urls')),
]

handler404 = error_404

tasker/forms.py
from django import forms
from django.utils.translation import gettext as _


class EnterNickForm(forms.Form):
    subscription_info = forms.CharField(widget=forms.HiddenInput)
    nick = forms.CharField(label=_('Nickname'), min_length=3, max_length=30)

tasker/views/attachments.py
from django.http import Http404

from . import FileView
from .. import decorators
from .. import models


try:
    from preview_generator.manager import PreviewManager

    preview_manager = PreviewManager('/tmp/preview_cache', create_folder=True)
    def get_preview_path(orig_path):
        return preview_manager.get_jpeg_preview(orig_path)

except ImportError:
    def get_preview_path(orig_path):
        return orig_path


class BaseView(FileView):
    def get_file_name(self, *args, **kwargs):
        attachment = models.Attachment.objects.get(pk=self.kwargs['attachment_id'])
        if attachment.handling.task.id != self.kwargs['task'].id:
            raise Http404
        return attachment.file.path


@decorators.class_decorator([decorators.board_view, decorators.task_view])
class PreviewView(BaseView):
    def get_file_name(self, *args, **kwargs):
        return get_preview_path(super().get_file_name(*args, **kwargs))


@decorators.class_decorator([decorators.board_view, decorators.task_view])
class FetchView(BaseView):
    pass

tasker/views/board.py
from datetime import timedelta
import string
import random

from django.urls import reverse, reverse_lazy
from django.utils.timezone import now
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q

from .tasks import TaskListBase
from .. import auth
from .. import utils
from .. import models
from .. import decorators


class CreateBoardView(CreateView):
    model = models.Board
    fields = ['label', 'admin_mail']

    def form_valid(self, form):
        # super().form_valid saves the object needed to create links
        return_value = super().form_valid(form)

        try:
            self.object.send_admin_mail(self.request)
        except ValueError:
            # expected iff user entered no admin mail
            pass

        return return_value

    def get_success_url(self):
        return utils.get_redirect_url(self.request, default=self.object.get_admin_url())


@decorators.class_decorator(decorators.board_view)
class BoardSendAdminLinkView(auth.AuthBoardMixin, TemplateView):
    template_name = 'tasker/board_adminlinksent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board'] = self.kwargs['board']

        old_admin_id = context['board'].admin_id

        # token does not has to be secure, just unique. hash will be applied afterwards
        new_auth_token = ''.join(random.choice(string.ascii_lowercase) for i in range(5))

        # only save changes if mail has been sent, otherwise we will exclude the admin
        try:
            self.kwargs['board'].admin_id = "{}:{}".format(self.kwargs['board'].id, new_auth_token)
            self.kwargs['board'].send_admin_mail(self.request)
        except ValueError as e:
            # restore admin_id to make links in navbar work
            self.kwargs['board'].admin_id = old_admin_id
            context['error'] = e.args[0]
        finally:
            self.kwargs['board'].save()

        return context


@decorators.class_decorator(decorators.board_admin_view)
class BoardAdminView(TaskListBase):
    template_name = 'tasker/board_admin.html'


@decorators.class_decorator(decorators.board_view)
class BoardSummaryView(auth.AuthBoardMixin, TemplateView):
    template_name = 'tasker/board_summary.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board'] = self.kwargs['board']

        context['tasks_done_simple'] = []
        context['tasks_done_complex'] = []
        context['tasks_not_done'] = []

        tasks = self.kwargs['board'].tasks.all()

        for task in tasks:
            if task.is_done():
                handlings = task.handlings.all()

                # do not use filter(...) here as we iterate over handlings later anyways
                total_duration = sum((handling.get_duration()
                                      for handling in handlings
                                      if handling.end is not None),
                                     timedelta(seconds=0))

                if len(handlings) == 0:
                    context['tasks_done_simple'].append((task, total_duration, None))
                elif all(not handling.tasker_comments.exists() and not handling.tasker_attachments.exists()
                         for handling in handlings):
                    context['tasks_done_simple'].append((task, total_duration, handlings.filter(success=True)[0]))
                else:
                    context['tasks_done_complex'].append(task)
            else:
                context['tasks_not_done'].append((task, task.get_current_handling().all()))

        return context


class BoardBaseView(auth.AuthBoardMixin, DetailView):
    model = models.Board
    lock_random_task = True

    def get_object(self):
        return self.kwargs['board']

    def get_open_tasks(self):
        return self.get_object().tasks \
            .filter(Q(done=False) & ~Q(hide_until__gt=now())) \
            .exclude(Q(requires__done=False) & ~Q(requires__hide_until__gt=now()))

    def get_filters(self):
        raise NotImplementedError

    def find_random_task(self):
        filters = self.get_filters()

        for search_filter in filters:
            result = list(search_filter.order_by('-priority', '?')[:1])
            if result:
                return result[0]

        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['random_task'] = self.find_random_task()
        return context


@decorators.class_decorator([decorators.board_view, decorators.require_name])
class BoardView(BoardBaseView):
    def get_filters(self):
        open_tasks = self.get_open_tasks()

        q_reserved = Q(reserved_until__gte=now())
        q_reserved_by_me = Q(reserved_until__gte=now(), reserved_by=self.kwargs['participant'])
        q_current_handling = Q(handlings__isnull=False, handlings__end__isnull=True)
        q_my_current_handling = Q(handlings__isnull=False, handlings__end__isnull=True, handlings__editor=self.kwargs['participant'])

        return [
            # my open tasks
            open_tasks.filter(q_my_current_handling | q_reserved_by_me),
            # tasks without reservation, excluding those with current handling
            open_tasks.filter(~q_reserved & ~q_current_handling),
            # tasks without reservation but current handling by others
            open_tasks.filter(~q_reserved & q_current_handling & ~q_my_current_handling),
        ]

    def get_context_data(self, **kwargs):
        # TODO transaction
        context = super().get_context_data(**kwargs)
        if context['random_task']:
            perform_locking = True

            # do not lock if globally unset
            if not self.lock_random_task:
                perform_locking = False

            # do not lock if it is already locked
            if perform_locking and context['random_task'].is_locked_for(self.kwargs['participant']):
                perform_locking = False

            # do not lock if we already got a handling
            context['handling_exists'] = False
            try:
                if perform_locking:
                    # should raise models.Handling.DoesNotExist
                    context['random_task'].get_current_handling(self.kwargs['participant'])
                    context['handling_exists'] = True
                    perform_locking = False
            except models.Handling.DoesNotExist:
                pass

            if perform_locking:
                assert context['random_task'].action_allowed('lock', self.kwargs['participant']), "Tried to lock task but locking is not allowed for this nick"
                context['random_task'].lock(self.kwargs['participant'])

        return context


@decorators.class_decorator([decorators.board_view])
class BoardMonitorView(BoardBaseView):
    template_name = "tasker/board_monitor.html"

    def get_filters(self):
        open_tasks = self.get_open_tasks()

        q_reserved = Q(reserved_until__gte=now())
        q_current_handling = Q(handlings__isnull=False, handlings__end__isnull=True)

        return [
            # tasks without reservation, excluding those with current handling
            open_tasks.filter(~q_reserved & ~q_current_handling),
        ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['random_task']:
            path = reverse('create_handling', kwargs={"board_slug": context['random_task'].board.slug, "task_id": context['random_task'].id})
            context['random_task_url'] = self.request.build_absolute_uri(path)
        return context


@decorators.class_decorator(decorators.board_admin_view)
class EditBoardView(auth.AuthBoardMixin, UpdateView):
    model = models.Board
    fields = ['label']

    def get_object(self):
        return self.kwargs['board']

    def get_success_url(self):
        return utils.get_redirect_url(self.request, default=self.object.get_admin_url())


@decorators.class_decorator(decorators.board_admin_view)
class DeleteBoardView(auth.AuthBoardMixin, DeleteView):
    model = models.Board
    success_url = reverse_lazy('start')

    def get_object(self):
        return self.kwargs['board']

tasker/views/nick.py
from django.urls import reverse
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View
from django.views.generic.edit import FormView

from . import ActionView
from .. import auth
from .. import forms
from .. import decorators
from .. import utils


@decorators.class_decorator(decorators.board_view)
class EnterNickView(auth.AuthBoardMixin, FormView):
    form_class = forms.EnterNickForm
    template_name = 'tasker/enter_nick.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board'] = self.kwargs['board']
        return context

    def form_valid(self, form):
        auth.login(self.request, self.kwargs['board'], form.cleaned_data['nick'], form.cleaned_data['subscription_info'])
        return super().form_valid(form)

    def get_success_url(self):
        return utils.get_redirect_url(self.request, default=reverse('start'))


@decorators.class_decorator([decorators.board_view, decorators.require_name])
class ResetNickView(auth.AuthBoardMixin, ActionView):
    default_pattern_name = 'start'

    def action(self, *args, **kwargs):
        auth.logout(self.request, self.kwargs['board'])


@method_decorator(csrf_exempt, name='dispatch')
class StoreWebPushView(View):
    def post(self, request, *args, **kwargs):
        auth.store_subscription_info(request, request.POST['subscription'])

        return JsonResponse({"success": True})

tasker/views/start.py
from django.shortcuts import render


def error_404(request, exception):
    return render(request, 'meta/error_404.html')

tasker/templates/task/base.html
{% load timedelta %}
{% load urlize %}
{% load i18n %}
{% load tasks %}

<div class="card" {% block card_settings %}{% endblock %}>
 <div class="card-header {% if task|task_status:participant == 'o' %}bg-secondary text-white{% elif task|task_status:participant == 'b' %}bg-warning{% elif task|task_status:participant == 'l' %}bg-danger text-white{% elif task|task_status:participant == 'r' %}bg-warning{% elif task|task_status:participant == 'p' %}bg-primary text-white{% elif task|task_status:participant == 'd' %}bg-success text-white{% endif %}">
  {% block task_label %}{{ task.label | escape }}{% endblock %}
 </div>
 {% block description %}
 <div class="card-body">
  <p class="card-text">{{ task.description | urlize_target_blank:30 | linebreaksbr }}</p>
 </div>
 {% endblock %}
 {% block handlings %}
 <ul class="list-group list-group-flush">
  {% for handling in task.handlings.all %}
   <li class="list-group-item">
    {% if handling.end %}
     <strong>{{ handling.editor.nick | escape }}</strong>
     <small>
      {% blocktrans with time_ago=handling.end|timesince duration=handling.get_duration|timedelta %}{{ time_ago }} ago for {{ duration }}{% endblocktrans %}
     </small>
     {% if handling.success %}<span class="badge bg-success">{% trans "Done" %}</span>
     {% else %}<span class="badge bg-danger">{% trans "Aborted" %}</span>
     {% endif %}
    {% else %}
     <strong>{{ handling.editor.nick }}</strong>
     <small>{% blocktrans with handling_since=handling.start|timesince %}{{ handling_since }} ago{% endblocktrans %}</small>
     <span class="badge bg-warning">{% trans "Active" %}</span>
    {% endif %}
    {% for comment in handling.tasker_comments.all %}
     <div class="alert alert-info">{{ comment.text | escape | linebreaksbr }}</div>
    {% endfor %}
    {% if handling.tasker_attachments %}
     <div class="row row-cols-1 row-cols-md-3">
     {% for attachment in handling.tasker_attachments.all %}
      <div class="col">
      <div class="card bg-dark text-white text-center">
       <img style="max-width:100%; max-height:200px; width:initial;" class="card-img" src="{% url 'preview_attachment' task.board.slug task.id attachment.id %}" />
       <div class="card-img-overlay">
        <a href="{% url 'fetch_attachment' task.board.slug task.id attachment.id %}" target="_blank" class="stretched-link"></a>
       </div>
      </div>
      </div>
     {% endfor %}
     </div>
    {% endif %}
   </li>
  {% endfor %}
 </ul>
 {% endblock %}
 {% block actions %}
 <div class="card-footer">
  {% if task.is_locked %}
   {% if task|task_status:participant in 'rp' %}
    <p>{% blocktrans with reserved_until=task.reserved_until|timeuntil %}Reserved for <strong>{{ reserved_until }}</strong>{% endblocktrans %}</p>
   {% else %}
    <p>{% blocktrans with reserved_by=task.reserved_by.nick|escape reserved_until=task.reserved_until|timeuntil %}Locked by <strong>{{ reserved_by }}</strong> for <strong>{{ reserved_until }}</strong>{% endblocktrans %}</p>
   {% endif %}
  {% endif %}
  {% if task.is_blocked %}
   <p>{% blocktrans %}Task is blocked by the following other tasks:{% endblocktrans %}</p>
   <div class="list-group">
    {% for blocking_task in task.get_blocking_tasks %}
     <a href="{% url 'show_task' blocking_task.board.slug blocking_task.id %}" class="list-group-item list-group-item-action">{{ blocking_task.label | escape }}</a>
    {% endfor %}
   </div>
  {% endif %}
  {% if 'start' in task|allowed_actions:participant %}{% block start_actions %}
   <a href="{% url 'create_handling' task.board.slug task.id %}" class="btn btn-primary">{% trans "Start" %}</a>
  {% endblock %}{% endif %}{% if 'stop' in task|allowed_actions:participant %}{% block stop_actions %}
   <a href="{% url 'abort_handling' task.board.slug task.id %}" class="btn btn-danger">{% trans "Abort" %}</a>
   <a href="{% url 'complete_handling' task.board.slug task.id %}" class="btn btn-success">{% trans "Done" %}</a>
  {% endblock %}{% endif %}{% if 'unlock' in task|allowed_actions:participant and not hide_lock_actions %}{% block unlock_actions %}
   <a href="{% url 'unlock_task' task.board.slug task.id %}" class="btn btn-warning">{% trans "Unlock" %}</a>
  {% endblock %}{% endif %}{% if 'lock' in task|allowed_actions:participant and not hide_lock_actions %}{% block lock_actions %}
   <a href="{% url 'lock_task' task.board.slug task.id %}" class="btn btn-warning">{% trans "Lock" %}</a>
  {% endblock %}{% endif %}{% if 'comment' in task|allowed_actions:participant %}{% block comment_actions %}
   <button class="btn btn-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseComment" aria-expanded="false" aria-controls="collapseComment">{% trans "Comment" %}</button>
   <button class="btn btn-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAttachment" aria-expanded="false" aria-controls="collapseAttachment">{% trans "Attach" %}</button>
   <div class="collapse" id="collapseComment">
   <form action="{% url 'comment_task' task.board.slug task.id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div id="div_id_text" class="form-group">
     <label for="id_text" class="col-form-label">{% trans "Comment:" %}</label>
     <div><textarea name="text" class="form-control" id="id_text"></textarea></div>
    </div>
    <input type="submit" class="btn btn-info" value="{% trans "Send" %}">
   </form>
   </div>
   <div class="collapse" id="collapseAttachment">
   <form action="{% url 'comment_task' task.board.slug task.id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div id="div_id_attachment" class="form-group">
     <label for="id_attachment" class="col-form-label">{% trans "Attachment:" %}</label>
     <div><input type="file" class="form-control-file" name="attachment" id="id_attachment"></div>
    </div>
    <input type="submit" class="btn btn-info" value="{% trans "Attach" %}">
   </form>
   </div>
  {% endblock %}{% endif %}
 </div>
 {% endblock %}
 {% block card_footer %}{% endblock %}
</div>

tasker/templates/task/board_admin.html
{% extends "task/base.html" %}

{% load i18n %}

{% block task_label %}
 {{ block.super }}
 {% if task.is_locked %}<span class="badge bg-warning">{% blocktrans with reserved_by=task.reserved_by.nick|escape reserved_until=task.reserved_until|timeuntil %}Locked by {{ reserved_by }} for {{ reserved_until }}{% endblocktrans %}</span>{% endif %}
 {% if task.is_blocked %}<span class="badge bg-warning">{% trans "Blocked" %}</span>{% endif %}
 {% if task.is_done %}<span class="badge bg-success">{% trans "Done" %}</span>{% endif %}
 {% if task.is_repeating %}<span class="badge bg-secondary">{% trans "Repeating" %}</span>{% endif %}
{% endblock %}

{% block handlings %}{% endblock %}

{% block actions %}
 <div class="card-footer">
  <a href="{% url 'show_task' task.board.slug task.id %}" class="btn btn-sm btn-info">{% trans "Show" %}</a>
  <a href="{% url 'edit_task' task.board.generate_hash task.id %}" class="btn btn-sm btn-secondary">{% trans "Edit" %}</a>
  <a href="{% url 'reset_task' task.board.generate_hash task.id %}" class="btn btn-sm btn-warning">{% trans "Reset" %}</a>
  <a href="{% url 'delete_task' task.board.generate_hash task.id %}" class="btn btn-sm btn-danger">{% trans "Delete" %}</a>
 </div>
{% endblock %}

tasker/templates/task/board_detail.html
{% extends "task/base.html" %}

{% load i18n %}

{% block unlock_actions %}
 <a href="{% url 'unlock_task' random_task.board.slug random_task.id %}?next={{ request.get_full_path|urlencode }}" class="btn btn-secondary">{% trans "Show new" %}</a>
{% endblock %}

tasker/templates/task/board_monitor.html
{% extends "task/base.html" %}

{% load i18n %}

{% block actions %}{% endblock %}

tasker/templates/task/board_summary.html
{% extends "task/base.html" %}

{% load timedelta %}
{% load i18n %}

{% block task_label %}<a href="{% url 'show_task' task.board.slug task.id %}">{{ block.super }}</a>{% endblock %}
{% block description %}{% endblock %}
{% block actions %}{% endblock %}
{% block card_footer %}
 <div class="card-footer text-end">
  <small>{% blocktrans with total_duration=total_duration|timedelta %}Total {{ total_duration }}{% endblocktrans %}</small>
 </div>
{% endblock %}