tasker/urls.py
from django.urls import path
from django.conf import settings
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

from .views import nick, board, tasks, handlings, attachments

urlpatterns = [
    path('', TemplateView.as_view(template_name='meta/start.html'), name='start'),
    path('meta/learn-more', TemplateView.as_view(template_name='meta/learn-more.html'), name='learn_more'),
    path('meta/imprint', TemplateView.as_view(template_name='meta/imprint.html'), name='imprint'),

    path('board/<slug:board_slug>/enter_nick', nick.EnterNickView.as_view(), name='enter_nick'),
    path('board/<slug:board_slug>/reset_nick', nick.ResetNickView.as_view(), name='reset_nick'),

    path('create_board/', board.CreateBoardView.as_view(), name='create_board'),

    path('board/<str:board_hash>/admin', board.BoardAdminView.as_view(), name='board_admin'),
    path('board/<str:board_hash>/edit', board.EditBoardView.as_view(), name='edit_board'),
    path('board/<str:board_hash>/delete', board.DeleteBoardView.as_view(), name='delete_board'),
    path('board/<str:board_hash>/create_task', tasks.CreateTaskView.as_view(), name='create_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/quickdone', tasks.QuickDoneTaskView.as_view(), name='quickdone_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/set_lock', tasks.SetLockTaskView.as_view(), name='set_task_lock'),
    path('board/<str:board_hash>/tasks/<int:task_id>/reset', tasks.ResetTaskView.as_view(), name='reset_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/edit', tasks.EditTaskView.as_view(), name='edit_task'),
    path('board/<str:board_hash>/tasks/<int:task_id>/delete', tasks.DeleteTaskView.as_view(), name='delete_task'),

    path('board/<slug:board_slug>', board.BoardView.as_view(), name='show_board'),
    path('board/<slug:board_slug>/monitor', board.BoardMonitorView.as_view(), name='board_monitor'),
    path('board/<slug:board_slug>/summary', board.BoardSummaryView.as_view(), name='board_summary'),
    path('board/<slug:board_slug>/tasks', tasks.TaskListView.as_view(), name='list_tasks'),
    path('board/<slug:board_slug>/request_link', board.BoardSendAdminLinkView.as_view(), name='request_board_link'),

    path('board/<slug:board_slug>/task/<int:task_id>', tasks.TaskView.as_view(), name='show_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/start', handlings.StartTaskView.as_view(), name='create_handling'),
    path('board/<slug:board_slug>/task/<int:task_id>/comment', handlings.CommentTaskView.as_view(), name='comment_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/abort', handlings.AbortTaskView.as_view(), name='abort_handling'),
    path('board/<slug:board_slug>/task/<int:task_id>/complete', handlings.CompleteTaskView.as_view(), name='complete_handling'),
    path('board/<slug:board_slug>/task/<int:task_id>/lock', tasks.LockTaskView.as_view(), name='lock_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/unlock', tasks.UnlockTaskView.as_view(), name='unlock_task'),
    path('board/<slug:board_slug>/task/<int:task_id>/attachment/<int:attachment_id>/preview', attachments.PreviewView.as_view(), name='preview_attachment'),
    path('board/<slug:board_slug>/task/<int:task_id>/attachment/<int:attachment_id>/fetch', attachments.FetchView.as_view(), name='fetch_attachment'),

    path('sw.js', TemplateView.as_view(template_name='tasker/sw.js', content_type='text/javascript'), name='jssw'),
    path('app.js', TemplateView.as_view(template_name='tasker/app.js', content_type='text/javascript', extra_context={'push_pubkey': settings.WEB_PUSH_KEYS[0]}), name='jsapp'),
    path('register_webpush', nick.StoreWebPushView.as_view(), name='webpush_register'),
    # TODO add caching
    path('jsi18n.js', JavaScriptCatalog.as_view(), name='jsi18n'),
]

troodle/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404

from tasker.views.start import error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasker.urls')),
]

handler404 = error_404

tasker/models.py
from datetime import timedelta
import json
from pywebpush import webpush, WebPushException

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.signing import Signer
from django.core.mail import EmailMessage
from django.utils.timezone import now
from django.template.loader import get_template
from django.utils.translation import gettext_lazy as _
from autoslug import AutoSlugField

BOARD_ADMIN_SIGNER = Signer(salt='board_admin')
ADMIN_MAIL_DELAY = timedelta(days=1)


class Board(models.Model):
    slug = AutoSlugField(_('slug'), populate_from='label', unique=True)
    label = models.CharField(_('label'), max_length=100)
    admin_id = models.CharField(_('admin id'), unique=True, max_length=30, help_text=_('id used to authenticate for admin interface'))
    admin_mail = models.EmailField(_('admin mail'), blank=True, null=True, help_text=_("Your Mailadress. Will only be used to send you mails with links to frontend and backend."))
    last_admin_mail_sent = models.DateTimeField(_('last time a mail to the admin was sent'), blank=True, null=True)
    cloned_from = models.ForeignKey('self', on_delete=models.CASCADE, related_name='clones', verbose_name=_('cloned from'), blank=True, null=True)
    created = models.DateTimeField(_('created'), auto_now_add=True)

    # used for django-admin
    def get_absolute_url(self):
        return self.get_admin_url()

    def get_admin_url(self):
        return reverse('board_admin', kwargs={'board_hash': self.generate_hash()})

    def get_frontend_url(self):
        return reverse('show_board', kwargs={'board_slug': self.slug})

    def generate_hash(self):
        return BOARD_ADMIN_SIGNER.sign(self.admin_id)

    @classmethod
    def get_by_hash(cls, board_hash):
        board_id = BOARD_ADMIN_SIGNER.unsign(board_hash)
        return cls.objects.get(admin_id=board_id)

    def send_admin_mail(self, request):
        # TODO use different exceptions
        if not self.admin_mail:
            raise ValueError(_("No Admin mail stored"))

        if self.last_admin_mail_sent and now() < self.last_admin_mail_sent + ADMIN_MAIL_DELAY:
            raise ValueError(_("Last admin mail has been sent too recently."))

        body = get_template("board_mail.txt").render({
            'label': self.label,
            'admin_link': request.build_absolute_uri(self.get_admin_url()),
            'frontend_link': request.build_absolute_uri(self.get_frontend_url()),
        })
        message = EmailMessage(to=[self.admin_mail], subject=_("Your Troodle-Board {label}").format(label=self.label), body=body)
        message.send()

        # reset counter
        self.last_admin_mail_sent = now()
        self.save()

    def __str__(self):
        return self.label

    def save(self):
        super().save()

        # check after saving to have pk initialized
        if not self.admin_id:
            self.admin_id = self.pk
            super().save()

    class Meta:
        ordering = ['created']
        verbose_name = _('Board')
        verbose_name_plural = _('Boards')


class Participant(models.Model):
    board = models.ForeignKey('Board', on_delete=models.CASCADE, related_name='participants', verbose_name=_('Board'))
    nick = models.CharField(_('Nick'), max_length=50)
    subscription_info = models.TextField(blank=True, null=True)

    def send_push(self, data):
        if self.subscription_info:
            try:
                webpush(
                    json.loads(self.subscription_info),
                    json.dumps(data),
                    vapid_private_key=settings.WEB_PUSH_KEYS[1],
                    vapid_claims={'sub': settings.WEB_PUSH_KEYS[2]})
            except WebPushException:
                # Purge subscription_info, once it failed
                self.subscription_info = None
                self.save()

    def __str__(self):
        return "{} ({})".format(self.nick, self.board)

    class Meta:
        verbose_name = _('Participant')
        verbose_name_plural = _('Participants')
        constraints = [
            models.UniqueConstraint(fields=['board', 'nick'], name='unique_nick'),
        ]


class Task(models.Model):
    OPEN = 'o'
    LOCKED = 'l'
    BLOCKED = 'b'
    RESERVED = 'r'
    PROCESSING = 'p'
    DONE = 'd'

    ACTIONS = {
        'lock': [OPEN],
        'unlock': [RESERVED],
        'start': [RESERVED],
        'stop': [PROCESSING],
        'comment': [PROCESSING],
    }

    slug = AutoSlugField(_('slug'), populate_from='label', unique_with=['board'])
    label = models.CharField(_('label'), max_length=100)
    board = models.ForeignKey('Board', on_delete=models.CASCADE, related_name='tasks', verbose_name=_('Board'))
    description = models.TextField(_('description'))
    done = models.BooleanField(_('done'), default=False)
    hide_until = models.DateTimeField(_('hide until'), blank=True, null=True)
    repeat_after = models.DurationField(_('repeat after'), blank=True, null=True, help_text=_('Never fully close this task, but automatically make it re-appear once the given duration passed after closing it.'))
    priority = models.IntegerField(_('priority'), default=100, help_text=_('Priority of this task: Tasks with higher priority will be shown before those with lower priority.'))
    reserved_by = models.ForeignKey('Participant', verbose_name=_("reserved by"), on_delete=models.SET_NULL, blank=True, null=True)
    reserved_until = models.DateTimeField(_('reserved until'), default=now)
    cloned_from = models.ForeignKey('self', on_delete=models.CASCADE, related_name='clones', verbose_name=_('cloned from'), blank=True, null=True)
    requires = models.ManyToManyField('self', symmetrical=False, related_name='required_by', verbose_name=_('requires'), blank=True, help_text=_("Tasks which have to be done before this task can be started."))

    def __str__(self):
        return _("{board}: {label}").format(board=self.board, label=self.label)

    def get_frontend_url(self):
        return reverse('show_task', kwargs={'board_slug': self.board.slug, 'task_id': self.id})

    def action_allowed(self, action, participant):
        return action in self.get_allowed_actions(participant)

    def get_allowed_actions(self, participant):
        participant_status = self.get_participant_status(participant)
        return [action for action, states in Task.ACTIONS.items() if participant_status in states]

    def get_participant_status(self, participant):
        try:
            self.get_current_handling(participant)
            return Task.PROCESSING
        except Handling.DoesNotExist:
            if self.is_done():
                return Task.DONE
            if self.is_blocked():
                return Task.BLOCKED
            if self.is_locked_for(participant):
                return Task.RESERVED
            if self.is_unlocked():
                return Task.OPEN
            return Task.LOCKED

    def get_current_handling(self, participant=None):
        query = self.handlings.filter(end__isnull=True)
        if participant:
            return query.get(editor=participant)
        return query

    def get_blocking_tasks(self):
        # filter only undone tasks from self.requires
        # undone must have done=False and hide_until either None or in the future
        return self.requires.filter(models.Q(done=False) & ~models.Q(hide_until__gt=now()))

    def is_done(self):
        return self.done or (self.hide_until is not None and self.hide_until > now())

    def is_blocked(self):
        return self.get_blocking_tasks().count() > 0

    def is_repeating(self):
        return self.repeat_after is not None

    def is_processing(self, participant):
        try:
            self.get_current_handling(participant)
            return True
        except Handling.DoesNotExist:
            return False

    def is_locked(self):
        return not self.is_unlocked()

    def is_unlocked(self):
        return now() > self.reserved_until

    def is_locked_for(self, participant):
        return self.reserved_by == participant and self.is_locked()

    def mark_done(self):
        if self.is_repeating():
            self.hide_until = now() + self.repeat_after
        else:
            self.done = True
        self.save()

    def unlock(self):
        self.reserved_until = now()
        self.save()

    def lock(self, participant, duration=None):
        # TODO refresh value, add transaction
        if self.is_locked() and not self.is_locked_for(participant):
            raise ValueError(_('Task is already locked'))

        if duration is None:
            duration = timedelta(seconds=30)

        self.reserved_by = participant
        self.reserved_until = now() + duration
        self.save()

    def send_push(self, data, ignore_participant=None, include_finished=False):
        participants = set([handling.editor for handling in self.handlings.all() if (include_finished or handling.end is None) and handling.editor != ignore_participant])
        for participant in participants:
            participant.send_push(data)

    class Meta:
        ordering = ['board', '-priority']
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')


class Handling(models.Model):
    task = models.ForeignKey('Task', on_delete=models.CASCADE, related_name='handlings', verbose_name=_('Task'))
    editor = models.ForeignKey('Participant', on_delete=models.CASCADE)
    start = models.DateTimeField(_('start'), default=now)
    end = models.DateTimeField(_('end'), blank=True, null=True)
    success = models.BooleanField(_('successfully'), blank=True, null=True)

    def get_duration(self):
        return self.end - self.start

    def __str__(self):
        # TODO add start / end if existing
        return _("{task} ({editor})").format(task=self.task, editor=self.editor)

    class Meta:
        ordering = ['task', 'start']
        verbose_name = _('Handling')

tasker/forms.py
from django import forms
from django.utils.translation import gettext as _


class EnterNickForm(forms.Form):
    subscription_info = forms.CharField(widget=forms.HiddenInput)
    nick = forms.CharField(label=_('Nickname'), min_length=3, max_length=30)

tasker/views/attachments.py
from django.http import Http404

from . import FileView
from .. import decorators
from .. import models


try:
    from preview_generator.manager import PreviewManager

    preview_manager = PreviewManager('/tmp/preview_cache', create_folder=True)
    def get_preview_path(orig_path):
        return preview_manager.get_jpeg_preview(orig_path)

except ImportError:
    def get_preview_path(orig_path):
        return orig_path


class BaseView(FileView):
    def get_file_name(self, *args, **kwargs):
        attachment = models.Attachment.objects.get(pk=self.kwargs['attachment_id'])
        if attachment.handling.task.id != self.kwargs['task'].id:
            raise Http404
        return attachment.file.path


@decorators.class_decorator([decorators.board_view, decorators.task_view])
class PreviewView(BaseView):
    def get_file_name(self, *args, **kwargs):
        return get_preview_path(super().get_file_name(*args, **kwargs))


@decorators.class_decorator([decorators.board_view, decorators.task_view])
class FetchView(BaseView):
    pass

tasker/views/nick.py
from django.urls import reverse
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import View
from django.views.generic.edit import FormView

from . import ActionView
from .. import auth
from .. import forms
from .. import decorators
from .. import utils


@decorators.class_decorator(decorators.board_view)
class EnterNickView(auth.AuthBoardMixin, FormView):
    form_class = forms.EnterNickForm
    template_name = 'tasker/enter_nick.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['board'] = self.kwargs['board']
        return context

    def form_valid(self, form):
        auth.login(self.request, self.kwargs['board'], form.cleaned_data['nick'], form.cleaned_data['subscription_info'])
        return super().form_valid(form)

    def get_success_url(self):
        return utils.get_redirect_url(self.request, default=reverse('start'))


@decorators.class_decorator([decorators.board_view, decorators.require_name])
class ResetNickView(auth.AuthBoardMixin, ActionView):
    default_pattern_name = 'start'

    def action(self, *args, **kwargs):
        auth.logout(self.request, self.kwargs['board'])


@method_decorator(csrf_exempt, name='dispatch')
class StoreWebPushView(View):
    def post(self, request, *args, **kwargs):
        auth.store_subscription_info(request, request.POST['subscription'])

        return JsonResponse({"success": True})

tasker/views/start.py
from django.shortcuts import render


def error_404(request, exception):
    return render(request, 'meta/error_404.html')

tasker/templates/tasker/board_admin.html
{% extends 'base_task_list.html' %}

{% load urlparser %}
{% load i18n %}

{% block title %}{{ board.label | escape }} &middot; {{ block.super }}{% endblock %}

{% block nav %}{% include "navbar/board.html" with board=board active='board_admin' %}{% endblock %}

{% block list %}
 <div class="btn-group mb-2">
  <a href="{% get_parameter show="list" !page %}" class="btn btn{% if request.GET.show and request.GET.show != 'list' %}-outline{% endif %}-info">{% trans "List" %}</a>
  <a href="{% get_parameter show="card" !page %}" class="btn btn{% if not request.GET.show or request.GET.show != 'card' %}-outline{% endif %}-info">{% trans "Card" %}</a>
 </div>
 {% if not request.GET.show or request.GET.show == 'list' %}
  {{ block.super }}
 {% else %}
  {% if object_list %}
   <div class="row" data-masonry='{"percentPosition": true}'>
    {% for object in object_list %}
     <div class="col-sm-12 col-lg-6 col-xl-4 mb-4">
     {% include 'task/board_admin.html' with task=object %}
     </div>
    {% endfor %}
   </div>
  {% else %}
   <p class="alert alert-info">{% trans "No tasks found." %}</p>
  {% endif %}
 {% endif %}
{% endblock %}

{% block task_label %}
 {{ block.super }}
 {% if object.is_locked %}<span class="badge bg-warning">{% blocktrans with reserved_by=object.reserved_by.nick|escape reserved_until=object.reserved_until|timeuntil %}Locked by {{ reserved_by }} for {{ reserved_until }}{% endblocktrans %}</span>{% endif %}
 {% if object.is_blocked %}<span class="badge bg-warning">{% trans "Blocked" %}</span>{% endif %}
 {% if object.is_done %}<span class="badge bg-success">{% trans "Done" %}</span>{% endif %}
 {% if object.is_repeating %}<span class="badge bg-secondary">{% trans "Repeating" %}</span>{% endif %}
{% endblock %}

{% block task_actions %}
 <span class="dropdown d-lg-none">
  <button class="btn btn-sm btn-primary dropdown-toggle" type="button" id="dropdown{{ object.id }}" data-bs-toggle="dropdown" aria-expanded="false">{% trans "Actions" %}</button>
  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown{{ object.pk }}">
   <a class="dropdown-item" href="{% url 'show_task' object.board.slug object.id %}">{% trans "Show" %}</a>
   <a class="dropdown-item" href="{% url 'edit_task' object.board.generate_hash object.id %}">{% trans "Edit" %}</a>
   <a class="dropdown-item" href="{% url 'set_task_lock' object.board.generate_hash object.id %}">{% trans "Lock" %}</a>
   <a class="dropdown-item" href="{% url 'quickdone_task' object.board.generate_hash object.id %}">{% trans "Mark as done" %}</a>
   <div class="dropdown-divider"></div>
   <a class="dropdown-item" href="{% url 'reset_task' object.board.generate_hash object.id %}">{% trans "Reset" %}</a>
   <a class="dropdown-item" href="{% url 'delete_task' object.board.generate_hash object.id %}">{% trans "Delete" %}</a>
  </div>
 </span>
 <span class="d-none d-lg-inline">
  <a href="{% url 'show_task' object.board.slug object.id %}" class="btn btn-info btn-sm">{% trans "Show" %}</a>
  <a href="{% url 'edit_task' object.board.generate_hash object.id %}" class="btn btn-secondary btn-sm">{% trans "Edit" %}</a>
  <a href="{% url 'set_task_lock' object.board.generate_hash object.id %}" class="btn btn-warning btn-sm">{% trans "Lock" %}</a>
  <a href="{% url 'quickdone_task' object.board.generate_hash object.id %}" class="btn btn-success btn-sm">{% trans "Mark as done" %}</a>
  <a href="{% url 'reset_task' object.board.generate_hash object.id %}" class="btn btn-warning btn-sm">{% trans "Reset" %}</a>
  <a href="{% url 'delete_task' object.board.generate_hash object.id %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
 </span>
{% endblock %}

{% block list_footer %}
 <tr>
  <td class="text-end">
   <a href="{% url 'create_task' board.generate_hash %}" class="btn btn-success btn-sm">{% trans "Create new" %}</a>
  </td>
 </tr>
{% endblock %}

{% block list_footer_empty %}
 <tr>
  {% url 'create_task' board.generate_hash as create_task_url %}
  <td colspan="2">{% blocktrans %}This board contains no tasks. Start by <a href="{{ create_task_url }}">creating one</a>{% endblocktrans %}</td>
 </tr>
{% endblock %}

{% block list_footer_filter_empty %}
 <tr>
  <td colspan="2">{% trans "No tasks found with current filters" %}</td>
 </tr>
{% endblock %}

tasker/templates/tasker/board_adminlinksent.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{{ board.label | escape }} &middot; {{ block.super }}{% endblock %}

{% block nav %}{% include "navbar/board.html" with board=board active='request_board_link' %}{% endblock %}

{% block content %}
 {% if error %}
  <p class="alert alert-danger">{{ error }}</p>
 {% else %}
  <p class="alert alert-info">{% trans "The admin will receive a mail shortly. Please note that previous links to the admin backend have been invalidated." %}</p>
 {% endif %}
{% endblock %}

tasker/templates/tasker/board_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{ object.label | escape }} &middot; {{ block.super }}{% endblock %}

{% block nav %}{% include "navbar/board.html" with board=object active='delete_board' %}{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
 <p class="alert alert-danger">{% blocktrans with board=object.label %}Are you sure you want to delete board "{{ board }}"?{% endblocktrans %}</p>
 <input type="submit" class="btn btn-danger" value="{% trans "Confirm" %}">
</form>
{% endblock %}

tasker/templates/tasker/board_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block nav %}{% include "navbar/board.html" with board=object active='board_detail' %}{% endblock %}

{% block title %}{{ board.label | escape }} &middot; {{ block.super }}{% endblock %}

{% block content %}
 {% if random_task %}
  {% if handling_exists %}<p class="alert alert-info">{% blocktrans %}You currently started a task. Please complete (or cancel) it first, before receiving a new task.{% endblocktrans %}</p>
  {% else %}<p class="alert alert-warning">{% blocktrans %}The random task shown below is just reserved for you. If you start working, please confirm by clicking "Start". To show another task, please use "Show New".{% endblocktrans %}</p>{% endif %}
  {% include 'task/board_detail.html' with task=random_task %}
 {% else %}
  {% url 'list_tasks' object.slug as list_tasks_url %}
  {% url 'board_summary' object.slug as board_summary_url %}
  <p class="alert alert-info">{% blocktrans %}No tasks could be found for you. Maybe take a look at the <a href="{{ list_tasks_url }}">list of all Tasks</a> or at the <a href="{{ board_summary_url }}">board summary</a>.{% endblocktrans %}</p>
 {% endif %}
{% endblock %}

tasker/templates/tasker/board_form.html
{% extends 'base_form.html' %}

{% load i18n %}

{% block title %}{% if object %}{{ object.label | escape }} &middot; {% endif %}{{ block.super }}{% endblock %}

{% block nav %}
 {% if object %}
  {% include 'navbar/board.html' with board=object active='edit_board' %}
 {% else %}
  {{ block.super }}
 {% endif %}
{% endblock %}

{% block message_create %}
 <p>{% blocktrans %}Welcome again to Troodle. Troodle enables you to work together with your team by hosting a hub of tasks to be done. Each of those hubs (called &quot;<em>board</em>&quot; at Troodle)
  will have two faces: The backend allows you to create, modify and delete tasks from the board while the frontend allows you and your team to work on tasks.{% endblocktrans %}</p>
 <p class="alert alert-info">{% blocktrans %}The Label should help you to identify the purpose of the hub. Remember that boards can be cloned to cope with repeating set of tasks, so make sure the label stays unique for you.{% endblocktrans %}</p>
{% endblock %}

tasker/templates/tasker/board_monitor.html
{% extends 'base.html' %}

{% load i18n %}
{% load qr_code %}

{% block nav %}{% include "navbar/board.html" with board=object active='board_detail' %}{% endblock %}

{% block title %}{{ board.label | escape }} &middot; {{ block.super }}{% endblock %}

{% block content %}
 {% if random_task %}
  <p class="alert alert-info">{% blocktrans %}Check the task below - if you like it, scan the QR-code on the left using your smartphone to start working.{% endblocktrans %}</p>

  <div class="float-start">
   {% qr_from_text random_task_url %}
  </div>
  <div>
   {% include 'task/board_monitor.html' with task=random_task %}
  </div>
 {% else %}
  <p class="alert alert-info">{% blocktrans %}Currently there are no open tasks waiting, please come back later!{% endblocktrans %}</p>
 {% endif %}
 <!--
 <div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
 </div>
 -->
 <script type="text/javascript">
  window.setTimeout(function() {window.location.reload()}, 30 * 1000);
 </script>
{% endblock %}

tasker/templates/tasker/enter_nick.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load i18n %}

{% block nav %}
 {% include 'navbar/board.html' with board=board active='enter_nick' %}
{% endblock %}

{% block content %}
 <p>{% blocktrans %}Welcome to Troodle. Troodle allows you to get tasks done as a team. It will randomly pick a task to work on and if you agree, it will protect the task from others colliding with your work.{% endblocktrans %}</p>
 <p>{% blocktrans %}To identify you, Troodle uses the concept of Nicknames. Pick one which identifies you unambiguously in the team you are working on:{% endblocktrans %}</p>
 <p>{% blocktrans %}You will be asked to accept notifications from this page. If you do so, we can inform you about changes regarding your current tasks.{% endblocktrans %}</p>
 <form method="post" id="nick_form">{% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-success" id="submit_button" value="{% trans "Enter" %}">
 </form>
{% endblock %}

{% block script %}
<script type="text/javascript">

$("#nick_form").submit(function (e, options) {
    options = options || {};

    if (!options.asked) {
        e.preventDefault();
        $("#submit_button").prop("disabled", true);
        requestPush().then(function (pushSubscription) {
            $("#id_subscription_info").val(JSON.stringify(pushSubscription));
            $("#nick_form").trigger('submit', {'asked': true});
        });
    }
});

</script>
{% endblock %}

tasker/templates/tasker/task_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{ object.label | escape }} &middot; {{ block.super }}{% endblock %}

{% block nav %}{% include "navbar/board.html" with board=object.board active='board_admin' %}{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
 <p class="alert alert-danger">{% blocktrans with task=object.label|escape board=object.board.label|escape %}Are you sure you want to delete task "{{ task }}" in board "{{ board }}"?{% endblocktrans %}</p>
 <input type="submit" class="btn btn-danger" value="{% trans "Confirm" %}">
</form>
{% endblock %}